<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Payment\Block\Transparent\Form $block */
$code = $block->escapeHtml($block->getMethodCode());
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
$ccType = $block->getInfoData('cc_type');
$content = '<img src=\"' . $block->getViewFileUrl('Magento_Checkout::cvv.png') . '\" alt=\"' .
    $block->escapeHtml(__('Card Verification Number Visual Reference')) . '\" title=\"' .
    $block->escapeHtml(__('Card Verification Number Visual Reference')) . '\" />';
?>

<!-- IFRAME for request to Payment Gateway -->
<iframe width="0" height="0" id="<?php /* @noescape */ echo $code; ?>-transparent-iframe"
        data-container="<?php /* @noEscape */ echo $code; ?>-transparent-iframe" allowtransparency="true"
        frameborder="0"  name="iframeTransparent" style="display:none;width:100%;background-color:transparent"
        src="<?php echo $block->escapeUrl($block->getViewFileUrl('blank.html')) ?>"></iframe>

    <fieldset class="fieldset ccard <?php /* @noEscape */ //echo $code; ?>" id="payment_form_<?php /* @noEscape */ echo $code; ?>">
 
     
        <div class="field required number">
            <label for="<?php /* @noEscape */ echo $code; ?>_cc_number" class="label">
                <span><?php echo $block->escapeHtml(__('Credit Card Number')); ?></span>
            </label>
            <div class="control">
				<input type="hidden" id="<?php /* @noEscape */ echo $code; ?>_cc_type" name="payment[cc_type]" 
                        data-validate='{
                            required:true,
                            "validate-cc-type-select":"#<?php /* @noEscape */ echo $code; ?>_cc_number"
                        }' />
						
                <input type="number" id="<?php /* @noEscape */ echo $code; ?>_cc_number"
                       data-container="<?php /* @noEscape */ echo $code; ?>-cc-number" name="payment[cc_number]"
                       title="<?php echo $block->escapeHtml(__('Credit Card Number')); ?>" class="input-text" value=""
                       data-validate='{
                           "validate-cc-number":"#<?php /* @noEscape */ echo $code; ?>_cc_type",
                           "validate-cc-type-alshaya":"#<?php /* @noEscape */ echo $code; ?>_cc_type"
                       }'
                       autocomplete="false"/>
            </div>
			<div class="clearboth"></div>
        </div>
        <div class="field required date" id="<?php /* @noEscape */ echo $code; ?>_cc_type_exp_div">
            <label for="<?php /* @noEscape */ echo $code; ?>_expiration" class="label">
                <span><?php echo $block->escapeHtml(__('Expiry Date')); ?></span>
            </label>
            <div class="control">
                <div class="fields group group-2">
                    <div class="field no-label month">
                        <div class="control">
                            <select id="<?php /* @noEscape */ echo $code; ?>_expiration" name="payment[cc_exp_month]"
                                    data-container="<?php /* @noEscape */ echo $code; ?>-cc-month" class="month cybersourcesmonth"
                                    data-validate='{
										requiredentry:true,
                                        "validate-cc-exp":"#<?php /* @noEscape */ echo $code; ?>_expiration_yr"
                                    }'>
                            <?php foreach ($block->getCcMonths() as $k => $v): ?>
                                <option value="<?php /* @noEscape */ echo $k ? $block->escapeHtml($k) : '' ?>"
                                    <?php if ($k == $ccExpMonth): ?> selected="selected"<?php endif; ?>>
                                    <?php echo $k; ?>
                                </option>
                            <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                    <div class="field no-label year">
                        <div class="control">
                            <select id="<?php /* @noEscape */ echo $code; ?>_expiration_yr" name="payment[cc_exp_year]"
                                    class="year" data-container="<?php /* @noEscape */ echo $code; ?>-cc-year"
                                    data-validate='{requiredentry:true}'>
                            <?php foreach ($block->getCcYears() as $k => $v): ?>
                                <option value="<?php /* @noEscape */ echo $k ? $block->escapeHtml($k) : ''; ?>"
                                    <?php if ($k == $ccExpYear): ?> selected="selected"<?php endif; ?>>
                                    <?php echo $block->escapeHtml($v); ?>
                                </option>
                            <?php endforeach ?>
                            </select>
                        </div>
                    </div>
					<div class="cybersourcesmontherror"></div>
                </div>
            </div>
			<div class="clearboth"></div>
        </div>
        <?php if ($block->hasVerification()): ?>
        <div class="field required cvv" id="<?php /* @noEscape */ echo $code; ?>_cc_type_cvv_div">
            <label for="<?php /* @noEscape */ echo $code; ?>_cc_cid" class="label">
                <span><?php echo $block->escapeHtml(__('Security Code')); ?></span>
            </label>
            <div class="control">
                <input type="number" title="<?php echo $block->escapeHtml(__('Card Verification Number')); ?>"
                       data-container="<?php /* @noEscape */ echo $code; ?>-cc-cvv" class="input-text cvv"
                       id="<?php /* @noEscape */ echo $code; ?>_cc_cid" name="payment[cc_cid]" value=""
                       data-validate='{
                           "validate-cc-cvn":"#<?php /* @noEscape */ echo $code;?>_cc_type"
                       }' autocomplete="false"/>
                <div class="note">
					<div class="whatsup"></div>
                    <div class="whatsup-content">
						<a href="#" id="<?php /* @noEscape */ echo $code; ?>-cvv-what-is-this" class="action cvv"
						   title="<?php echo $block->escapeHtml(__('What is this?'));?>" data-mage-init='{
							   "tooltip": {"content": "<?php /* @noEscape */ echo $content; ?>"}
						   }'>
							<span><?php echo $block->escapeHtml(__('This code is a three or four digits number printed on the front or back on the credit card')); ?></span>
						</a>
					</div>
					<div class="clearboth"></div>
                </div>
				<div class="clearboth"></div>
            </div>
			<div class="clearboth"></div>
        </div>
        <?php endif; ?>
    <?php echo $block->getChildHtml() ?>
</fieldset>
<div class="verisignlogo"></div>
<div class="clearboth"></div>



<script>
    require([
        'jquery',
        'underscore',
        'Magento_Payment/js/model/credit-card-validation/credit-card-number-validator/credit-card-type'
    ], function ($, _, creditCardTypes) {
         $('#cybersource_cc_number').on('change keyup paste', function () {
			var value = $(this).val();
			potentialTypes = creditCardTypes.getCardTypes(value);	
            //alert(JSON.stringify(potentialTypes, null, 4));
    
			if (potentialTypes.length === 0) {
				$('#cybersource_cc_type').val('');
				$('.credit-card-types .item').css({ opacity: 0.2 });
                return false;
            } 
			
            cardType = potentialTypes[0];
			var availableTypes = window.checkoutConfig.payment.ccform.availableTypes.<?php echo $code; ?>;
			var availableTypesFinal = _.map(availableTypes, function(value, key) {
                    return {
                        'value': key,
                        'type': value
                    }
                });
			var title = '';
			_.each(availableTypesFinal, function (value) {
                    if (value['value'] == cardType.type) {
                        title = value['type'];
                    }
             });			
        
			$('.credit-card-types .item').css({ opacity: 1 });
            
			if(title){
				$('#cybersource_cc_type').val(cardType.type);
				$('.credit-card-types .item').css({ opacity: 0.2 });
				$('.credit-card-types .'+cardType.type.toLowerCase()).css({ opacity: 1 });
                return true;				
			}
            else{
                $('#cybersource_cc_type').val('');
                $('.credit-card-types .item').css({ opacity: 0.2 });
                return false;
            }
			
    });
    });
</script>
<script>
require([
    "jquery",
	"mage/validation",
	"mage/translate" 
], function($){
	'use strict';



	$('#cybersource_cc_number').blur(
		function() {
			$.validator.validateElement($(this));
		}
	);
	 $('#cybersource_expiration').blur(
			function() {
				$.validator.validateElement($(this));
			 }
	);
	$('#cybersource_expiration_yr').blur(
			function() {
				$.validator.validateElement($('#cybersource_expiration'));
			 }
	);
	$('#cybersource_cc_cid').blur(
			function() {
				$.validator.validateElement($(this));
			 }
	); 
});
</script>